apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podpri-pic-frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pic-frontend.lb.djnd.si
      secretName: podpri-pic-frontend-tls
  rules:
    - host: pic-frontend.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podpri-pic-frontend
                port:
                  number: 80
