apiVersion: batch/v1
kind: CronJob
metadata:
  name: pair-mautic-contacs-conjob
spec:
  schedule: 49 3 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pair-mautic-contacs-conjob
            image: podpri
            command:
              - python
              - manage.py
              - pair_contacts_with_mauitc
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: djndonacije.settings.k8s
            envFrom:
              - secretRef:
                  name: podpri-credentials
            resources:
              requests:
                memory: 400Mi
                cpu: 200m
              limits:
                memory: 400Mi
                cpu: 200m
          restartPolicy: Never
