apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic-5-deployment
  labels:
    app: mautic-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic-5
  template:
    metadata:
      labels:
        app: mautic-5
    spec:
      containers:
        - name: mautic-5
          image: mautic/mautic:5.1-apache
          ports:
            - containerPort: 80
          envFrom:
              - secretRef:
                  name: mautic-5-credentials
          resources:
            requests:
              memory: 2000Mi
              cpu: 1000m
            limits:
              memory: 2000Mi
              cpu: 1000m
