apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautic-5
  labels:
    app: mautic-5
spec:
  serviceName: mautic-5-sfc
  selector:
    matchLabels:
      app: mautic-5
  template:
    metadata:
      labels:
        app: mautic-5
    spec:
      containers:
        - name: mautic-5
          image: mautic/mautic:5.1.1-fpm
          ports:
            - containerPort: 80
          envFrom:
              - secretRef:
                  name: mautic-5-credentials
          resources:
            requests:
              memory: 2000Mi
              cpu: 1000m
            limits:
              memory: 2000Mi
              cpu: 1000m
          volumeMounts:
            - mountPath: /var/www/html
              name: mautic-5-static
              subPath: mautic
      volumes:
        - name: mautic-5-static
          persistentVolumeClaim:
            claimName: mautic-5-volumeclaim

  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mautic-5-static
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: scw-bssd-retain
        resources:
          requests:
            storage: "1Gi"
