# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_auto_20171002_2049"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payer_id",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
