# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_article_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="Category",
            new_name="category",
        ),
    ]
