# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_auto_20171003_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
