# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='session',
            field=models.CharField(max_length=64),
        ),
    ]
