# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 13:09
from __future__ import unicode_literals

import datetime

import django.utils.timezone
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_article_mergable"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(2018, 4, 5, 13, 9, 20, 829456, tzinfo=timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basket",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(2018, 4, 5, 13, 9, 30, 271395, tzinfo=timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basket",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
