# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_order_is_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_on_cebelca",
            field=models.BooleanField(default=False),
        ),
    ]
