# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-23 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_auto_20180823_0807"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boundleitem",
            name="quantity",
        ),
    ]
