# Generated by Django 2.2.10 on 2020-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200118_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='variant_of',
            field=models.ForeignKey(blank=True, limit_choices_to={'variant_of': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.Article', verbose_name='variant of'),
        ),
    ]
