# Generated by Django 2.2.10 on 2021-01-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20201130_1518'),
        ('shop', '0021_auto_20201127_1126'),
    ]

    operations = [
    ]
