# Generated by Django 3.2.8 on 2022-02-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_merge_20210104_0759"),
        ("shop", "0022_order_transaction_id"),
    ]

    operations = []
