apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautic-deployment
  labels:
    app: mautic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic
  template:
    metadata:
      labels:
        app: mautic
    spec:
      containers:
        - name: mautic
          image: mautic/mautic:v4
          ports:
            - containerPort: 80
          envFrom:
              - secretRef:
                  name: mautic-credentials
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
            limits:
              memory: 300Mi
              cpu: 200m
