on:
  push:
    branches:
    - main

jobs:
  pull-requests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: pull-request-k8s
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "k8s"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Pulling ${{ github.ref }} into k8s"
