# Generated by Django 2.2.3 on 2019-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0002_auto_20190529_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='mautic_id',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mautic_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='Anonimnež_ica', max_length=128),
        ),
    ]
