# Generated by Django 2.2.3 on 2019-12-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0006_auto_20191214_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
