# Generated by Django 2.2.3 on 2019-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0007_subscriber_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='nonce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
