# Generated by Django 2.2.1 on 2019-12-16 13:47

from django.db import migrations, models

import djnd_supporters.models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0008_gift_nonce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[djnd_supporters.models.OptionalSchemeURLValidator()],
            ),
        ),
    ]
