# Generated by Django 2.2.1 on 2020-02-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0009_auto_20191216_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringDonation',
            fields=[
                ('donation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djnd_supporters.Donation')),
                ('subscription_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('djnd_supporters.donation',),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='nonce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
