# Generated by Django 2.2.10 on 2020-11-27 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0009_auto_20191216_1347"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringDonation",
            fields=[
                (
                    "donation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="djnd_supporters.Donation",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("djnd_supporters.donation",),
        ),
    ]
