# Generated by Django 2.2.10 on 2021-01-04 08:00

from django.db import migrations, models
import djnd_supporters.models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0011_auto_20201130_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='typ',
            field=models.CharField(choices=[('PARLAMETER_SI', 'PARLAMETER_SI'), ('PARLAMETER_HR', 'PARLAMETER_HR'), ('PARLAMETER_BA', 'PARLAMETER_BA'), ('DJND', 'DJND')], default=djnd_supporters.models.DonationType('DJND'), max_length=255),
        ),
    ]
