# Generated by Django 2.2.10 on 2021-01-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0012_donation_typ"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of donation campaign", max_length=32
                    ),
                ),
                (
                    "has_upn",
                    models.BooleanField(default=True, help_text="Enable UPN donation"),
                ),
                (
                    "has_braintree",
                    models.BooleanField(
                        default=True, help_text="Enable braintree donation"
                    ),
                ),
                (
                    "upn_email_template",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of email template on mautic for UPN donation",
                        null=True,
                    ),
                ),
                (
                    "bt_email_template",
                    models.IntegerField(
                        blank=True,
                        help_text="Id of email tempalte on mautic for braintree donation",
                        null=True,
                    ),
                ),
                (
                    "add_to_mailing",
                    models.IntegerField(
                        blank=True, help_text="Add email to this mailing ID", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="donation",
            name="typ",
        ),
        migrations.AddField(
            model_name="donation",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djnd_supporters.DonationCampaign",
            ),
        ),
    ]
