# Generated by Django 2.2.10 on 2021-08-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0016_donation_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='upn_name',
            field=models.CharField(default='Donacija', help_text='Name for upn description', max_length=32),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='djnd_supporters.DonationCampaign'),
        ),
    ]
