# Generated by Django 3.2.8 on 2021-10-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0018_auto_20211028_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdonation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
