# Generated by Django 3.2.8 on 2022-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0018_donationcampaign_has_upload_image"),
        ("djnd_supporters", "0019_recurringdonation_is_active"),
    ]

    operations = []
