# Generated by Django 3.2.8 on 2022-01-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0020_merge_20220113_1342"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("nonce", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=20),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="djnd_supporters.donationcampaign",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="djnd_supporters.subscriber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("nonce", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=20),
                ),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.CharField(default="braintree", max_length=50),
                ),
                ("reference", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="djnd_supporters.donationcampaign",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="djnd_supporters.subscriber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="donation",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="subscriber",
        ),
        migrations.RemoveField(
            model_name="recurringdonation",
            name="donation_ptr",
        ),
        migrations.DeleteModel(
            name="Gift",
        ),
        migrations.AlterField(
            model_name="image",
            name="donation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="djnd_supporters.transaction",
            ),
        ),
        migrations.DeleteModel(
            name="Donation",
        ),
        migrations.DeleteModel(
            name="RecurringDonation",
        ),
    ]
