# Generated by Django 3.2.8 on 2022-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0029_alter_donationcampaign_web_hook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField(blank=True, help_text='Question for verification', null=True)),
                ('answear', models.TextField(blank=True, help_text='Answers for verification', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
