# Generated by Django 3.2.8 on 2023-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0033_auto_20230117_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedamount',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
