# Generated by Django 3.2.8 on 2023-01-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0034_alter_predefinedamount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='css'),
        ),
        migrations.AddField(
            model_name='donationcampaign',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Redirect url on success', null=True),
        ),
    ]
