# Generated by Django 3.2.8 on 2024-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0041_remove_donationcampaign_add_to_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcampaign',
            name='css_file_url',
            field=models.URLField(blank=True, help_text='Povezava do CSS datoteke s stili za frontend', null=True),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='braintee_subscription_plan_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Braintree subscription plan id'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='bt_email_template',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za braintree donacijo'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='bt_subscription_email_template',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za braintree mesečno donacijo (prvi email)'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='charged_unsuccessfully_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za neuspešno obračunano braintree mesečno donacijo'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='edit_subscriptions_email_tempalte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic ID emaila za urejanje naročnine'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='has_braintree',
            field=models.BooleanField(default=True, verbose_name='Sprejemamo braintree enkratne donacije?'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='has_braintree_subscription',
            field=models.BooleanField(default=True, verbose_name='Sprejemamo braintree mesečne donacije?'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='has_upn',
            field=models.BooleanField(default=True, verbose_name='Sprejemamo UPN donacije?'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Ime donacijske kampanje'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='segment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic segment ID'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='slug',
            field=models.CharField(help_text='Male črke, brez presledkov (primer: danes-je-nov-dan). Je sestavni del URL-ja na frontendu za novičnike in donacije (npr. moj.djnd.si/danes-je-nov-dan/doniraj)', max_length=32, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='subscription_canceled_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za preklic braintree mesečnih donacij'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='subscription_charged_successfully',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za uspešno obračunano braintree mesečno donacijo'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Prikaže se na https://moj.djnd.si/&lt;slug&gt;/doniraj', null=True, verbose_name='Podnaslov'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='title',
            field=models.CharField(blank=True, help_text='Prikaže se na https://moj.djnd.si/&lt;slug&gt;/doniraj', max_length=256, null=True, verbose_name='Naslov'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='upn_email_template',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za UPN donacijo'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='upn_name',
            field=models.CharField(blank=True, default='Donacija', max_length=32, null=True, verbose_name='UPN namen na plačilnem nalogu'),
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='welcome_email_tempalte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mautic email ID za welcome mail'),
        ),
    ]
