# Generated by Django 3.2.8 on 2024-03-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0041_remove_donationcampaign_add_to_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Novičnik', max_length=128)),
                ('slug', models.CharField(max_length=32)),
                ('title', models.CharField(help_text='Naslov', max_length=256)),
                ('subtitle', models.TextField(blank=True, help_text='Opis', null=True)),
                ('segment', models.IntegerField(blank=True, help_text='ID of mautic segment of this campaign. Used for mailings.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='donationcampaign',
            name='segment',
            field=models.IntegerField(blank=True, help_text='ID of mautic segment of this campaign. Used for mailings.', null=True),
        ),
    ]
