# Generated by Django 3.2.8 on 2024-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0044_remove_donationcampaign_css_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcampaign",
            name="has_flik",
            field=models.BooleanField(
                default=False, verbose_name="Sprejemamo flik donacije?"
            ),
        ),
    ]
