# Generated by Django 5.2.7 on 2025-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0045_donationcampaign_has_flik"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donationcampaign",
            old_name="bt_email_template",
            new_name="onetime_donation_email_template",
        ),
        migrations.AlterField(
            model_name="donationcampaign",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="predefinedamount",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
