# Generated by Django 5.2.7 on 2026-04-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnd_supporters', '0049_donationcampaign_flik_subscription_cancelled_email_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='djnd_supporters.subscription'),
        ),
    ]
