# Generated by Django 5.2.7 on 2026-05-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0050_transaction_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Ime računa")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="djnd_supporters.account",
            ),
        ),
        migrations.CreateModel(
            name="FlikApi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Ime/lastnik Flik API ključa"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(max_length=128, verbose_name="Flik API ključ"),
                ),
                (
                    "shared_secret",
                    models.CharField(
                        help_text="Secure secret za flik donacije",
                        max_length=32,
                        verbose_name="Flik SS",
                    ),
                ),
                (
                    "obb_api_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Flik OBB API ključ",
                    ),
                ),
                (
                    "obb_shared_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secure secret za flik OBB donacije",
                        max_length=32,
                        null=True,
                        verbose_name="Flik OBB SS",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=128, verbose_name="Flik username"),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="Flik password"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flik_apis",
                        to="djnd_supporters.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="flik_api",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="djnd_supporters.flikapi",
            ),
        ),
        migrations.CreateModel(
            name="Iban",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "company_name",
                    models.CharField(max_length=128, verbose_name="Ime podjetja"),
                ),
                ("iban", models.CharField(max_length=34, verbose_name="IBAN")),
                ("address_1", models.TextField(verbose_name="Ulica")),
                ("address_2", models.TextField(verbose_name="Pošta")),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ibans",
                        to="djnd_supporters.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="iban",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="djnd_supporters.iban",
            ),
        ),
    ]
