# Generated by Django 5.2.7 on 2026-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0051_account_transaction_account_flikapi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flikapi",
            name="obb_shared_secret",
            field=models.CharField(
                blank=True,
                help_text="Secure secret za flik OBB donacije",
                max_length=128,
                null=True,
                verbose_name="Flik OBB SS",
            ),
        ),
        migrations.AlterField(
            model_name="flikapi",
            name="shared_secret",
            field=models.CharField(
                help_text="Secure secret za flik donacije",
                max_length=128,
                verbose_name="Flik SS",
            ),
        ),
    ]
