# Generated by Django 5.2.7 on 2026-05-12 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0052_alter_flikapi_obb_shared_secret_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BraintreeApi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Ime/lastnik Braintree API ključa"
                    ),
                ),
                (
                    "env",
                    models.CharField(
                        choices=[("production", "production"), ("sandbox", "sandbox")],
                        default="production",
                        max_length=32,
                        verbose_name="Braintree environment",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        max_length=128, verbose_name="Braintree merchant id"
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        max_length=128, verbose_name="Braintree public key"
                    ),
                ),
                (
                    "private_key",
                    models.CharField(
                        max_length=128, verbose_name="Braintree private key"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="braintree_apis",
                        to="djnd_supporters.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
