# Generated by Django 5.2.7 on 2026-05-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0053_braintreeapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="djnd_supporters.account",
            ),
        ),
    ]
