# Generated by Django 5.2.7 on 2026-05-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0054_subscription_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcampaign",
            name="flik_subscription_timeout_email_template",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Mautic email ID za potek flik mesečne donacije",
            ),
        ),
        migrations.CreateModel(
            name="CampaignQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("question", models.CharField(max_length=256)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link for question, e.g. to explain why you are asking this question. Terms of use, privacy policy, etc.",
                        max_length=256,
                        null=True,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "field_type",
                    models.CharField(
                        choices=[("checkbox", "checkbox")],
                        default="checkbox",
                        max_length=32,
                    ),
                ),
                (
                    "donation_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="djnd_supporters.donationcampaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
