# Generated by Django 5.2.7 on 2026-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djnd_supporters",
            "0055_donationcampaign_flik_subscription_timeout_email_template_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignquestion",
            name="segment_id",
            field=models.IntegerField(
                blank=True,
                help_text="Mautic segment ID that will be applied to subscriber if they check the box for this question",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaignquestion",
            name="field_type",
            field=models.CharField(
                choices=[("segment_checkbox", "segment_checkbox")],
                default="segment_checkbox",
                max_length=32,
            ),
        ),
    ]
