# Generated by Django 5.2.7 on 2026-05-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0056_campaignquestion_segment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcampaign",
            name="braintree_api",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="djnd_supporters.braintreeapi",
            ),
        ),
    ]
