# Generated by Django 5.2.7 on 2026-05-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0057_donationcampaign_braintree_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignquestion",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional file for question, e.g. to explain why you are asking this question. Terms of use, privacy policy, etc.",
                null=True,
                upload_to="question_files",
            ),
        ),
        migrations.AddField(
            model_name="campaignquestion",
            name="question_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="campaignquestion",
            name="question_sl",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="subtitle_sl",
            field=models.TextField(
                blank=True,
                help_text="Prikaže se na https://moj.djnd.si/&lt;slug&gt;/doniraj",
                null=True,
                verbose_name="Podnaslov",
            ),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="terms_of_use",
            field=models.FileField(
                blank=True,
                help_text="Pogoji doniranja - datoteka se prikaže kot povezava na strani z donacijami",
                null=True,
                upload_to="terms_of_use",
            ),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="terms_of_use_text",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Pogoji doniranja - besedilo, ki se prikaže namesto povezave, npr. 'Pogoji doniranja'",
            ),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="terms_of_use_text_en",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Pogoji doniranja - besedilo, ki se prikaže namesto povezave, npr. 'Pogoji doniranja'",
            ),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="terms_of_use_text_sl",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Pogoji doniranja - besedilo, ki se prikaže namesto povezave, npr. 'Pogoji doniranja'",
            ),
        ),
        migrations.AddField(
            model_name="donationcampaign",
            name="title_sl",
            field=models.CharField(
                blank=True,
                help_text="Prikaže se na https://moj.djnd.si/&lt;slug&gt;/doniraj",
                max_length=256,
                null=True,
                verbose_name="Naslov",
            ),
        ),
        migrations.AlterField(
            model_name="donationcampaign",
            name="subtitle_en",
            field=models.TextField(
                blank=True,
                help_text="Prikaže se na https://moj.djnd.si/&lt;slug&gt;/doniraj",
                null=True,
                verbose_name="Podnaslov",
            ),
        ),
        migrations.AlterField(
            model_name="donationcampaign",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Prikaže se na https://moj.djnd.si/&lt;slug&gt;/doniraj",
                max_length=256,
                null=True,
                verbose_name="Naslov",
            ),
        ),
    ]
