# Generated by Django 5.2.7 on 2026-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djnd_supporters",
            "0058_campaignquestion_file_campaignquestion_question_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignquestion",
            name="url_text",
            field=models.CharField(
                blank=True,
                help_text="Besedilo, ki se prikaže namesto URL-ja, npr. 'Terms of use'",
                max_length=256,
                null=True,
                verbose_name="Besedilo povezave",
            ),
        ),
        migrations.AddField(
            model_name="campaignquestion",
            name="url_text_en",
            field=models.CharField(
                blank=True,
                help_text="Besedilo, ki se prikaže namesto URL-ja, npr. 'Terms of use'",
                max_length=256,
                null=True,
                verbose_name="Besedilo povezave",
            ),
        ),
        migrations.AddField(
            model_name="campaignquestion",
            name="url_text_sl",
            field=models.CharField(
                blank=True,
                help_text="Besedilo, ki se prikaže namesto URL-ja, npr. 'Terms of use'",
                max_length=256,
                null=True,
                verbose_name="Besedilo povezave",
            ),
        ),
    ]
