# Generated by Django 5.2.7 on 2026-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0059_campaignquestion_url_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignquestion",
            name="add_to_newsletter_confirmation_required",
            field=models.BooleanField(
                default=False, verbose_name="Prijava na novičnik zahteva potrditev"
            ),
        ),
        migrations.AddField(
            model_name="campaignquestion",
            name="welcome_email_tempalte",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Mautic email ID za welcome mail"
            ),
        ),
    ]
