# Generated by Django 5.2.7 on 2026-05-19 10:21

import django.db.models.deletion
from django.db import migrations, models


def forwards_create_braintree_customers(apps, schema_editor):
    Subscriber = apps.get_model("djnd_supporters", "Subscriber")
    BraintreeApi = apps.get_model("djnd_supporters", "BraintreeApi")
    BraintreeCustomer = apps.get_model("djnd_supporters", "BraintreeCustomer")

    if not BraintreeApi.objects.filter(id=1).exists():
        return

    existing_pairs = set(
        BraintreeCustomer.objects.filter(braintree_api_id=1).values_list(
            "subscriber_id", "customer_id"
        )
    )

    customers_to_create = []
    subscribers = Subscriber.objects.exclude(customer_id__isnull=True).exclude(
        customer_id=""
    )
    for subscriber in subscribers.iterator():
        key = (subscriber.id, subscriber.customer_id)
        if key in existing_pairs:
            continue
        customers_to_create.append(
            BraintreeCustomer(
                subscriber_id=subscriber.id,
                braintree_api_id=1,
                customer_id=subscriber.customer_id,
            )
        )

    if customers_to_create:
        BraintreeCustomer.objects.bulk_create(customers_to_create)


class Migration(migrations.Migration):

    dependencies = [
        (
            "djnd_supporters",
            "0060_campaignquestion_add_to_newsletter_confirmation_required_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BraintreeCustomer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "customer_id",
                    models.CharField(
                        max_length=128, verbose_name="Braintree customer id"
                    ),
                ),
                (
                    "braintree_api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djnd_supporters.braintreeapi",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="braintree_customers",
                        to="djnd_supporters.subscriber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            forwards_create_braintree_customers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
