# Generated by Django 5.2.7 on 2026-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0061_auto_20260519_1021"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="referrer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="referrer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
