# Generated by Django 5.2.7 on 2026-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0062_subscription_referrer_transaction_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignquestion",
            name="question",
            field=models.TextField(
                help_text="Besedilo vprašanja. Če se začne z 'html:' potem se bo interpretiralo kot html, npr. za dodajanje linkov, odebelitev, ipd. V htmlju lahko uporabiš '{file_url}' za povezavo do datoteke, ostali linki definirani v spodnjih poljih se ne upoštevajo - dodaj jih direktno v html.",
                verbose_name="Vprašanje",
            ),
        ),
        migrations.AlterField(
            model_name="campaignquestion",
            name="question_en",
            field=models.TextField(
                help_text="Besedilo vprašanja. Če se začne z 'html:' potem se bo interpretiralo kot html, npr. za dodajanje linkov, odebelitev, ipd. V htmlju lahko uporabiš '{file_url}' za povezavo do datoteke, ostali linki definirani v spodnjih poljih se ne upoštevajo - dodaj jih direktno v html.",
                null=True,
                verbose_name="Vprašanje",
            ),
        ),
        migrations.AlterField(
            model_name="campaignquestion",
            name="question_sl",
            field=models.TextField(
                help_text="Besedilo vprašanja. Če se začne z 'html:' potem se bo interpretiralo kot html, npr. za dodajanje linkov, odebelitev, ipd. V htmlju lahko uporabiš '{file_url}' za povezavo do datoteke, ostali linki definirani v spodnjih poljih se ne upoštevajo - dodaj jih direktno v html.",
                null=True,
                verbose_name="Vprašanje",
            ),
        ),
    ]
