# Generated by Django 5.2.7 on 2026-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0063_alter_campaignquestion_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignquestion",
            name="file",
        ),
        migrations.AlterField(
            model_name="campaignquestion",
            name="question",
            field=models.TextField(
                help_text="Besedilo vprašanja. Če se začne z 'html:' potem se bo interpretiralo kot html, npr. za dodajanje linkov, odebelitev, ipd. V htmlju se link definiran spodaj ne upošteva - dodaj linke direktno v html.",
                verbose_name="Vprašanje",
            ),
        ),
        migrations.AlterField(
            model_name="campaignquestion",
            name="question_en",
            field=models.TextField(
                help_text="Besedilo vprašanja. Če se začne z 'html:' potem se bo interpretiralo kot html, npr. za dodajanje linkov, odebelitev, ipd. V htmlju se link definiran spodaj ne upošteva - dodaj linke direktno v html.",
                null=True,
                verbose_name="Vprašanje",
            ),
        ),
        migrations.AlterField(
            model_name="campaignquestion",
            name="question_sl",
            field=models.TextField(
                help_text="Besedilo vprašanja. Če se začne z 'html:' potem se bo interpretiralo kot html, npr. za dodajanje linkov, odebelitev, ipd. V htmlju se link definiran spodaj ne upošteva - dodaj linke direktno v html.",
                null=True,
                verbose_name="Vprašanje",
            ),
        ),
    ]
