# Generated by Django 5.2.7 on 2026-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0064_remove_campaignquestion_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
