# Generated by Django 5.2.7 on 2026-06-16 13:26

from django.db import migrations
from django.db.models import F


def copy_created_to_transaction_timestamp(apps, schema_editor):
    Transaction = apps.get_model("djnd_supporters", "Transaction")
    Transaction.objects.all().update(transaction_timestamp=F("created"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0065_transaction_transaction_timestamp"),
    ]

    operations = [
        migrations.RunPython(
            copy_created_to_transaction_timestamp,
            reverse_code=noop_reverse,
        ),
    ]
