# Generated by Django 5.2.7 on 2026-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0066_auto_20260616_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="disbursement_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
