# Generated by Django 5.2.7 on 2026-07-09 12:38

from django.db import migrations, models

import djnd_supporters.models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0066_auto_20260616_1327"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeUID",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "uid",
                    models.CharField(
                        default=djnd_supporters.models._generate_uid,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
