# Generated by Django 5.2.7 on 2026-07-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0067_onetimeuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="disbursement_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
