# Generated by Django 5.2.7 on 2026-07-09 20:09

from django.db import migrations, models


def backfill_disbursement_timestamp(apps, schema_editor):
    Transaction = apps.get_model("djnd_supporters", "Transaction")
    Transaction.objects.filter(
        is_paid=True,
        disbursement_timestamp__isnull=True,
        transaction_timestamp__isnull=False,
    ).update(disbursement_timestamp=models.F("transaction_timestamp"))


class Migration(migrations.Migration):

    dependencies = [
        ("djnd_supporters", "0067_transaction_disbursement_timestamp"),
    ]

    operations = [
        migrations.RunPython(
            backfill_disbursement_timestamp,
            migrations.RunPython.noop,
        ),
    ]
